import React, { useState, useEffect } from 'react';
import type { Project, Profile, Template } from '../types';
import { supabase } from '../src/lib/supabaseClient';
import { ArrowLeftIcon } from '../components/Icons';

interface ProjectDetailPageProps {
  project: Project;
  user: Profile;
  onBack: () => void;
  onProjectUpdate: (project: Project) => void;
}

export const ProjectDetailPage: React.FC<ProjectDetailPageProps> = ({ project, user, onBack, onProjectUpdate }) => {
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [currentProject, setCurrentProject] = useState<Project>(project);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setCurrentProject(project);
  }, [project]);

  const generateSlug = (base: string) => {
    return base.trim().toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  };

  const generatePublicUrl = (slug: string) => {
    const origin = window.location.origin;
    return `${origin}/r/${slug}`;
  };

  const handleLogoUpload = async (file: File) => {
    const ext = file.name.split('.').pop();
    const fileName = `${user.id}-${currentProject.id}-logo-${Date.now()}.${ext}`;
    setUploading(true);
    setUploadError(null);
    const { error } = await supabase.storage.from('project_logos').upload(fileName, file);
    if (error) {
      setUploadError(error.message);
      setUploading(false);
      return null;
    }
    const { data } = supabase.storage.from('project_logos').getPublicUrl(fileName);
    setUploading(false);
    return data.publicUrl;
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      // Remove frontend slug generation, rely on backend trigger
      const payload: Partial<Project> = {
        ...currentProject,
        updated_at: new Date().toISOString(),
        // The slug will be generated by the backend trigger if not provided or empty
        // The qr_code_url will be generated based on the final slug by the backend or a separate process
        // For now, we'll keep the public_url generation for immediate UI feedback if slug is present
        qr_code_url: currentProject.slug ? `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${generatePublicUrl(currentProject.slug)}` : null,
      };

      const { data, error } = await supabase
        .from('projects')
        .update(payload)
        .eq('id', currentProject.id)
        .select('*, templates(*)') // Re-fetch templates to get updated field_mapping if needed
        .maybeSingle();

      if (error) throw error;

      if (data) {
        setCurrentProject(data);
        onProjectUpdate(data);
      }
      setSaving(false);
    } catch (e: any) {
      console.error(e);
      alert('Save error: ' + (e?.message || String(e)));
      setSaving(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto animate-fade-in-up">
      <button onClick={onBack} className="flex items-center space-x-2 text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white mb-6">
        <ArrowLeftIcon className="h-4 w-4" />
        <span>Back to Projects</span>
      </button>

      <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
        <div className="p-6 border-b border-slate-200 dark:border-slate-800">
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">{currentProject.project_name || currentProject.id}</h1>
          <p className="text-slate-500 dark:text-slate-400">Template: {currentProject.templates?.template_name || 'N/A'}</p>
          {!currentProject.template_category && (
            <div className="mt-4 p-4 bg-yellow-100 dark:bg-yellow-900 border border-yellow-200 dark:border-yellow-800 rounded-md">
              <p className="text-sm text-yellow-700 dark:text-yellow-200">
                Template category not found. Please reassign a template to this project.
              </p>
            </div>
          )}
        </div>
        <div className="p-6">
          <h3 className="font-semibold text-slate-800 dark:text-slate-200 mb-4">Customize Project</h3>
          {currentProject.templates?.instructions && (
            <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">{currentProject.templates.instructions}</p>
          )}
          {currentProject.templates?.use_cases && (
            <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">{currentProject.templates.use_cases}</p>
          )}
          <div className="space-y-4">
            <label className="block text-sm">
              <div className="text-slate-600 dark:text-slate-300 mb-1">Project Name</div>
              <input
                value={currentProject.project_name || ''}
                onChange={(e) => setCurrentProject(prev => ({ ...prev, project_name: e.target.value }))}
                className="w-full bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded px-3 py-2"
              />
            </label>

            {currentProject.templates?.field_mapping &&
              Object.entries(currentProject.templates.field_mapping).map(([genericField, semanticRole]) => (
                <label key={genericField} className="block text-sm">
                  <div className="text-slate-600 dark:text-slate-300 mb-1">{semanticRole}</div>
                  <input
                    value={(currentProject as any)[genericField] || ''}
                    onChange={(e) => setCurrentProject(prev => ({ ...prev, [genericField]: e.target.value }))}
                    className="w-full bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded px-3 py-2"
                  />
                </label>
              ))}

            <label className="block text-sm">
              <div className="text-slate-600 dark:text-slate-300 mb-1">Theme Color</div>
              <input
                type="color"
                value={currentProject.theme_color || '#0ea5a4'}
                onChange={(e) => setCurrentProject(prev => ({ ...prev, theme_color: e.target.value }))}
              />
            </label>

            <label className="block text-sm">
              <div className="text-slate-600 dark:text-slate-300 mb-1">Logo Upload (optional)</div>
              <input
                type="file"
                accept="image/*"
                onChange={async (e) => {
                  if (!e.target.files || !e.target.files[0]) return;
                  const publicUrl = await handleLogoUpload(e.target.files[0]);
                  if (publicUrl) setCurrentProject(prev => ({ ...prev, logo_url: publicUrl }));
                }}
              />
              {uploading && <div className="text-sm text-slate-500 mt-2">Uploading...</div>}
              {uploadError && <div className="text-sm text-red-500 mt-2">{uploadError}</div>}
            </label>

            <label className="block text-sm">
              <div className="text-slate-600 dark:text-slate-300 mb-1">Slug (public path)</div>
              <input
                value={currentProject.slug || ''}
                onChange={(e) => setCurrentProject(prev => ({ ...prev, slug: e.target.value }))}
                className="w-full bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded px-3 py-2"
                placeholder="my-awesome-project"
              />
            </label>

            <div className="flex items-center space-x-3 mt-6">
              <button onClick={handleSave} disabled={saving} className="px-4 py-2 bg-primary-600 text-white rounded">{saving ? 'Saving...' : 'Save & Publish'}</button>
              <button onClick={() => setCurrentProject(project)} className="px-4 py-2 border rounded">Reset</button>
            </div>
          </div>
        </div>
      </div>
      {currentProject.qr_code_url && (
        <div className="mt-6 bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
          <div className="p-6">
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">Shareable Link & QR Code</h2>
            <div className="flex items-center space-x-4">
              <div className="flex-shrink-0">
                <img src={currentProject.qr_code_url} alt="QR Code" className="w-32 h-32" />
              </div>
              <div className="flex-grow">
                <p className="text-sm text-slate-600 dark:text-slate-400">Your public link:</p>
                <a href={currentProject.slug ? generatePublicUrl(currentProject.slug) : '#'} target="_blank" rel="noreferrer" className="text-primary-600 dark:text-primary-400 font-medium break-all">{currentProject.slug ? generatePublicUrl(currentProject.slug) : 'N/A'}</a>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProjectDetailPage;
