CREATE TABLE feedbacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text,
    "time" time,
    "date" date,
    feedback text,
    Stars integer,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
